"""agregar estado a responsable

Revision ID: 7123242bdbed
Revises: d1be422f27c2
Create Date: 2026-05-18 23:40:33.037369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7123242bdbed'
down_revision: Union[str, Sequence[str], None] = 'd1be422f27c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "responsable",
        sa.Column(
            "estado",
            sa.String(length=50),
            nullable=False,
            server_default="laborando",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responsable', 'estado')
    # ### end Alembic commands ###
