"""agregar estado conexion y fuera empresa

Revision ID: afa1b143742a
Revises: e44a5417b605
Create Date: 2026-05-17 22:34:19.068983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa1b143742a'
down_revision: Union[str, Sequence[str], None] = 'e44a5417b605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activo",
        sa.Column(
            "estado_conexion",
            sa.String(length=30),
            nullable=False,
            server_default="conectado",
        ),
    )
    op.add_column(
        "activo",
        sa.Column(
            "fuera_empresa",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activo', 'fuera_empresa')
    op.drop_column('activo', 'estado_conexion')
    # ### end Alembic commands ###
