"""vincular usuario con responsable

Revision ID: d1be422f27c2
Revises: 3719bb2c01d6
Create Date: 2026-05-17 23:54:41.387735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1be422f27c2'
down_revision: Union[str, Sequence[str], None] = '3719bb2c01d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('id_responsable', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'usuario', ['id_responsable'])
    op.create_foreign_key(None, 'usuario', 'responsable', ['id_responsable'], ['id_responsable'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_column('usuario', 'id_responsable')
    # ### end Alembic commands ###
