"""crear tablas iniciales

Revision ID: e44a5417b605
Revises: 
Create Date: 2026-05-12 21:17:15.690409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44a5417b605'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_mapa',
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('coord_x_inicio', sa.Integer(), nullable=False),
    sa.Column('coord_y_inicio', sa.Integer(), nullable=False),
    sa.Column('coord_x_fin', sa.Integer(), nullable=False),
    sa.Column('coord_y_fin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_area'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_area_mapa_id_area'), 'area_mapa', ['id_area'], unique=False)
    op.create_table('responsable',
    sa.Column('id_responsable', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_responsable')
    )
    op.create_index(op.f('ix_responsable_correo'), 'responsable', ['correo'], unique=True)
    op.create_index(op.f('ix_responsable_id_responsable'), 'responsable', ['id_responsable'], unique=False)
    op.create_table('tipo_activo',
    sa.Column('id_tipo_activo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_activo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipo_activo_id_tipo_activo'), 'tipo_activo', ['id_tipo_activo'], unique=False)
    op.create_table('activo',
    sa.Column('id_activo', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('id_tipo_activo', sa.Integer(), nullable=False),
    sa.Column('id_responsable', sa.Integer(), nullable=False),
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('es_movil', sa.Boolean(), nullable=False),
    sa.Column('coord_x_actual', sa.Float(), nullable=False),
    sa.Column('coord_y_actual', sa.Float(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_area'], ['area_mapa.id_area'], ),
    sa.ForeignKeyConstraint(['id_responsable'], ['responsable.id_responsable'], ),
    sa.ForeignKeyConstraint(['id_tipo_activo'], ['tipo_activo.id_tipo_activo'], ),
    sa.PrimaryKeyConstraint('id_activo'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_index(op.f('ix_activo_codigo'), 'activo', ['codigo'], unique=True)
    op.create_index(op.f('ix_activo_id_activo'), 'activo', ['id_activo'], unique=False)
    op.create_table('asignacion_trabajo',
    sa.Column('id_asignacion', sa.Integer(), nullable=False),
    sa.Column('id_responsable', sa.Integer(), nullable=False),
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_area'], ['area_mapa.id_area'], ),
    sa.ForeignKeyConstraint(['id_responsable'], ['responsable.id_responsable'], ),
    sa.PrimaryKeyConstraint('id_asignacion')
    )
    op.create_index(op.f('ix_asignacion_trabajo_id_asignacion'), 'asignacion_trabajo', ['id_asignacion'], unique=False)
    op.create_table('ubicacion_historial',
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('id_activo', sa.Integer(), nullable=False),
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('coord_x', sa.Float(), nullable=False),
    sa.Column('coord_y', sa.Float(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_activo'], ['activo.id_activo'], ),
    sa.ForeignKeyConstraint(['id_area'], ['area_mapa.id_area'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_index(op.f('ix_ubicacion_historial_id_historial'), 'ubicacion_historial', ['id_historial'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ubicacion_historial_id_historial'), table_name='ubicacion_historial')
    op.drop_table('ubicacion_historial')
    op.drop_index(op.f('ix_asignacion_trabajo_id_asignacion'), table_name='asignacion_trabajo')
    op.drop_table('asignacion_trabajo')
    op.drop_index(op.f('ix_activo_id_activo'), table_name='activo')
    op.drop_index(op.f('ix_activo_codigo'), table_name='activo')
    op.drop_table('activo')
    op.drop_index(op.f('ix_tipo_activo_id_tipo_activo'), table_name='tipo_activo')
    op.drop_table('tipo_activo')
    op.drop_index(op.f('ix_responsable_id_responsable'), table_name='responsable')
    op.drop_index(op.f('ix_responsable_correo'), table_name='responsable')
    op.drop_table('responsable')
    op.drop_index(op.f('ix_area_mapa_id_area'), table_name='area_mapa')
    op.drop_table('area_mapa')
    # ### end Alembic commands ###
